name: Elasticsearch Java Test

on:
  pull_request:
    paths:
      - "elasticsearch-java/**"
      - "policies/**"
  push:
    tags:
      - elasticsearch-java/v*

defaults:
  run:
    working-directory: elasticsearch-java

jobs:
  test:
    strategy:
      matrix:
        java-version: ["17", "21"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4

      - name: Build and test
        run: gradle build --no-daemon
